name: Plan Declarative Migrations
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/atlas-plan-push.yaml
      - 'schema.sql'
  pull_request:
    branches:
      - master
      - main
    paths:
      - .github/workflows/atlas-plan-push.yaml
      - 'schema.sql'
permissions:
  contents: read
  pull-requests: write
jobs:
  plan:
    name: plan
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Atlas
        uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_TOKEN }}
      - name: Run schema plan
        uses: ariga/atlas-action/schema/plan@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          env: dev
  approve-push:
    name: approve-push
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Atlas
        uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_TOKEN }}
      # Plan against the latest schema state (one before the PR).
      - name: Approve the plan
        id: plan-approve
        uses: ariga/atlas-action/schema/plan/approve@v1
        with:
          env: dev
      # Push the schema after the plan is approved.
      - name: Push the schema
        id: schema-push
        uses: ariga/atlas-action/schema/push@v1
        with:
          env: dev